name:                HaskellCoin
version:             0.0.1.0
github:              "MasterLogick/HaskellCoin"
license:             BSD3
author:              "MasterLogick"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Yet another blockchain but written in Haskell this time

dependencies:
- base >= 4.7 && < 5
- text >= 1.2.4.0
- basement == 0.0.12
- cryptonite >= 0.29
- bytestring == 0.11.3.1
- binary >= 0.8.8.0
- network >= 3.1.2.7
- memory >= 0.17.0
library:
  source-dirs: src

executables:
  HaskellCoin-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskellCoin
